config/routes.rb
Rails.application.routes.draw do
  
  resources :comments
  
  get 'posts/feed', to: 'posts#feed', as: :feed
  delete 'posts/destroy/:id', to: 'posts#destroy', as: :post_destroy
  resources :posts
  
  post 'posts/:id/comments', to: 'comments#create', as: :comment_post
  get 'posts/comment/:id', to: 'comments#edit', as: :edit_comment_post
  patch 'posts/:id/like', to: 'posts#like', as: :like_post
  patch 'posts/:id/dislike', to: 'posts#dislike', as: :dislike_post
  
  
  # Rotas de UserController
  get 'users/admin', to: 'users#crud', as: :admin
  get 'users', to: 'users#index', as: :users
  get 'users/new', to: 'users#new', as: :user_new
  post 'users/new', to: 'users#create'
  get 'users/:id', to: 'users#show', as: :user
  get 'users/edit/:id', to: 'users#edit', as: :user_edit
  patch 'users/edit/:id', to: 'users#update'
  delete 'users/destroy/:id', to: 'users#destroy', as: :user_destroy
  
  #Rotas de SessionsController
  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: :logout
  

  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user,  optional: true
  belongs_to :post
  
  validates :content, length: {in:5..50}
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :non_logged_user, except: [:new,:create]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_or_correct_user, only: :destroy

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    post = Post.find(params[:id])
    @comment = post.comments.build(comment_params)
    
    if logged_in?
      @comment.user_id = current_user.id
    end

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :content, :post_id)
    end
    
    def correct_user
      if @comment.user != current_user
        redirect_to posts_path
      end
    end
    
    def admin_or_correct_user
      if !current_user.admin && (@comment.user != current_user)
        redirect_to articles_path
      end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :comment_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Content</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user.name %></td>
        <td><%= comment.content %></td>
        <td><%= comment.post.title %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post.title %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>