config/routes.rb
Rails.application.routes.draw do
  
  resources :comments
  
  get 'posts/feed', to: 'posts#feed', as: :feed
  delete 'posts/destroy/:id', to: 'posts#destroy', as: :post_destroy
  resources :posts
  
  post 'posts/:id/comments', to: 'comments#create', as: :comment_post
  get 'posts/comment/:id', to: 'comments#edit', as: :edit_comment_post
  patch 'posts/:id/like', to: 'posts#like', as: :like_post
  patch 'posts/:id/dislike', to: 'posts#dislike', as: :dislike_post
  
  
  # Rotas de UserController
  get 'users/admin', to: 'users#crud', as: :admin
  get 'users', to: 'users#index', as: :users
  get 'users/new', to: 'users#new', as: :user_new
  post 'users/new', to: 'users#create'
  get 'users/:id', to: 'users#show', as: :user
  get 'users/edit/:id', to: 'users#edit', as: :user_edit
  patch 'users/edit/:id', to: 'users#update'
  delete 'users/destroy/:id', to: 'users#destroy', as: :user_destroy
  
  #Rotas de SessionsController
  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: :logout
  

  
end

app/models/user.rb
class User < ApplicationRecord
  
  has_secure_password
  
  validates :name, length: { in: 2..50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, length: { in: 10..50}, format: { with: VALID_EMAIL_REGEX }
  #allow_nil permite que voce nao precise redigitar a senha quando editar o usuario
  validates :password, length: { in: 3..6, presence: true, allow_nil: true }
  
  
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :like_posts ,dependent: :destroy
  has_many :dislike_posts ,dependent: :destroy
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :destroy, :update]
    #before_action :user_params, only: [:create, :update]
    
    before_action :logged_user, only: [:new, :create]
    before_action :non_logged_user, except: [:new, :create]
    before_action :non_admin, only: :index
    before_action :correct_user_or_admin,only: [:edit,:update,:destroy]
    
    def crud
        @users = User.paginate(:page => params[:page], :per_page => 5)
    end
    
    def new 
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
           redirect_to user_path(@user)
        else
            render :new
        end
    end
    
    def show
    end
    
    def edit
    end
    
    def update
        if @user.update_attributes(user_params)
            redirect_to user_path(@user)
        else
            render :edit
        end
    end
    
    def index
        #Variaveis com @ sao variaveis de instancia
        #elas ficam disponiveis para as views
        @users = User.all
    end
    
    def destroy
        if @user == current_user
            log_out
        end
        
        @user.destroy
        
        redirect_to users_path
    end
    
    private
    
    def set_user
       @user = User.find(params[:id]) 
    end
    
    def user_params
        @user_params = params.require(:user).permit(:name, :email, :password, :password_confirmation, :feeder, :profile_photo)
    end
    
    def correct_user_or_admin
       if !(current_user == @user || current_user.admin)
           redirect_to user_path(current_user)
       end
    end
    
    def non_admin
      if !current_user
        redirect_to login_path
      end
      if (current_user && !current_user.admin)
        redirect_to user_path(current_user.id)
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, url: @user.persisted? ? user_edit_path : user_new_path do |f| %>
    <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    
    <% if current_user && current_user == @user || !@user.persisted? %>
    
        Nome: <%= f.text_field :name %><br />
        
        Email: <%= f.text_field :email %><br />
        
        Senha: <%= f.password_field :password %><br />
        
        Confirmação de Senha: <%= f.password_field :password_confirmation %><br />
        
    <% end %>
    
    <% if current_user && current_user.admin %>
        Gerador de conteudo: <%= f.check_box :feeder %><br />
    <% end %>
    
    <%= f.submit "Enviar" %>
  
<% end %>

app/views/users/crud.html.erb
<% provide(:title, "Usuarios | ")%>
<p id="notice"><%= notice %></p>

<h1>Users Admin</h1>

<table id="users_adm">
  <thead>
    <tr>
      <th>User</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user_path(user) %></td>
        <td><%= link_to 'Edit', user_edit_path(user) %></td>
        <td><%= link_to 'Destroy', user_destroy_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="navPag">
  <%= will_paginate @users %>
</div>
<script>
  $('#users_adm').DataTable({});
</script>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', user_edit_path(user) %></td>
        <td><%= link_to 'Destroy', user_destroy_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New User', user_new_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', user_edit_path(@user) %> |
<%= link_to 'Back', users_path %>