config/routes.rb
Rails.application.routes.draw do
  
  resources :comments
  
  get 'posts/feed', to: 'posts#feed', as: :feed
  delete 'posts/destroy/:id', to: 'posts#destroy', as: :post_destroy
  resources :posts
  
  post 'posts/:id/comments', to: 'comments#create', as: :comment_post
  get 'posts/comment/:id', to: 'comments#edit', as: :edit_comment_post
  patch 'posts/:id/like', to: 'posts#like', as: :like_post
  patch 'posts/:id/dislike', to: 'posts#dislike', as: :dislike_post
  
  
  # Rotas de UserController
  get 'users/admin', to: 'users#crud', as: :admin
  get 'users', to: 'users#index', as: :users
  get 'users/new', to: 'users#new', as: :user_new
  post 'users/new', to: 'users#create'
  get 'users/:id', to: 'users#show', as: :user
  get 'users/edit/:id', to: 'users#edit', as: :user_edit
  patch 'users/edit/:id', to: 'users#update'
  delete 'users/destroy/:id', to: 'users#destroy', as: :user_destroy
  
  #Rotas de SessionsController
  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: :logout
  

  
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, PictureUploader
  
  validates :title, length: {in: 2..50}
  validate  :picture_size
  validate  :post_content
  
  
  belongs_to :user
  
  has_many :comments, dependent: :destroy
  has_many :like_posts ,dependent: :destroy
  has_many :dislike_posts ,dependent: :destroy

  def picture_size
    if image.size > 2.megabytes
      errors.add(:image, "imagem não pode ser maior a 2 megabytes")
    end
  end
  
  def post_content
    if image.length > 0
              if content.length > 0
                errors.add(content, "nao pode postar 2 coisas   linha 23")
              end
    else
      
      if content.length < 2 || content.length > 140
        errors.add(content, "conteudo fora dos limites  linha 28")
      end
    end
  end
  
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like, :dislike]
  before_action :non_logged_user, except: [:show,:feed]
  before_action :correct_user, only: [:edit,:update]
  before_action :admin_or_correct_user, only: :destroy
  before_action :non_admin, only: [:index]
  #after_action :destroy, only: [:dislike], if: -> { @odiado }
  
  #def teste
  #  redirect_to post_destroy_path(@post.id)
  #end
  
  
  def feed
        @posts = Post.paginate(:page => params[:page], :per_page => 5)
  end
  
  # GET /posts
  # GET /posts.json
  def index
    # paginate
    @posts = Post.paginate(:page => params[:page], :per_page => 5)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    
    @comment = Comment.new
    @comments = @post.comments
    
    if logged_in?
      @liked = LikePost.find_by(user_id: current_user.id, post_id: @post.id)
      @disliked = DislikePost.find_by(user_id: current_user.id, post_id: @post.id)
    end
    
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    
    @post = current_user.posts.build(post_params)
    # if !(@post.content.empty? && (@post.image.size>0)?)
      
      respond_to do |format|
          if @post.save
            format.html { redirect_to @post, notice: 'Post was successfully created.' }
            format.json { render :show, status: :created, location: @post }
          else
            format.html { render :new }
            format.json { render json: @post.errors, status: :unprocessable_entity }
          end
      end  
    
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to feed_path, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
    
  end



  def like
    like = LikePost.find_by(post_id: @post.id, user_id: current_user.id)
    
    if like.nil?
      LikePost.create(post_id: @post.id, user_id: current_user.id)
    else
      like.destroy
    end
    
    dislike = DislikePost.find_by(post_id: @post.id, user_id: current_user.id)
    dislike.destroy if dislike
    
    @liked = LikePost.find_by(user_id: current_user.id, post_id: @post.id)
    
    respond_to do |format|
      format.html { redirect_to @post }
      format.js
    end
    
  end


  def dislike

    dislike = DislikePost.find_by(post_id: @post.id, user_id: current_user.id)
    if dislike.nil?
      DislikePost.create(post_id: @post.id, user_id: current_user.id)
    else
      dislike.destroy
    end
    like = LikePost.find_by(post_id: @post.id, user_id: current_user.id)
    like.destroy if like
    
    @disliked = DislikePost.find_by(user_id: current_user.id, post_id: @post.id)
    respond_to do |format|
      format.html { redirect_to @post }
      format.js
    end
    
    #@odiado = false
    if  DislikePost.count(:id == @post.id) > 14 # o numero vai ser o valor limite
      #@odiado = true
      # redirect_to post_destroy_path(@post.id)
      @post.destroy
      flash[:error] = "Esse post foi deletado por completar 15 dislikes."
      respond_to do |format|
        format.html {redirect_to feed_path}
        format.js {render plain: "window.location = '/posts/feed';"}
      end
    end
  end


  private
  
  
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:user_id, :title, :content, :image)
    end
        
    
    def correct_user
      if @post.user != current_user
        redirect_to posts_path
      end
    end
    
    def admin_or_correct_user
      if !current_user.admin && current_user != @post.user
        redirect_to posts_path
      end
    end
    
    def non_admin
      if !current_user
        redirect_to login_path
      end
      if (current_user && !current_user.admin)
        redirect_to user_path(current_user.id)
      end
    end
    
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_dislike.html.erb
<% if @disliked %>
      <%= link_to "Descurtiu #{@post.dislike_posts.count}", dislike_post_path, method: :patch, id: "descurtir", remote: true, authenticity_token: true %>
<% else %>
  <%= link_to "Descurtir #{@post.dislike_posts.count}" , dislike_post_path, method: :patch, id: "descurtir", remote: true, authenticity_token: true %>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :post_content %>
  </div>

  <%= form.file_field :image %><br />

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_like.html.erb
<% if @liked %>
  <%= link_to "Curtiu #{@post.like_posts.count}", like_post_path, method: :patch, id: "curtir", remote: true, authenticity_token: true %>
<% else %>
  <%= link_to "Curtir #{@post.like_posts.count}", like_post_path, method: :patch, id: "curtir", remote: true, authenticity_token: true %>
<% end %>

app/views/posts/dislike.js.erb
$("#descurtir").replaceWith("<%= escape_javascript(render('posts/dislike')) %>");
$("#curtir").replaceWith("<%= escape_javascript(render('posts/like')) %>");

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/feed.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Postar Ideia', new_post_path, class: "postar" %>
<h1>Feed</h1>

<table id="posts">
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Conteudo ou Imagem do post</th>
    
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td>
          <!--mostrar texto ou imagem que foi postada-->
        <% if post.image_url.present? %>
          <%= image_tag(post.image_url, size: "50") %>
        <% else %>
          <%= post.content %>
        <% end  %>
        </td>
        <!--a opção de DESTROY somente vai aparecer parao dono do post-->
        
        <td colspan=3><%= link_to 'Show', post %></td>
        
        <% if current_user  && (post.user_id == current_user.id || current_user.admin) %>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Certeza ?' } %></td>
        <% end %>
          
      </tr>
    <% end %>
  </tbody>
</table>
<div class="navPag">
  <%= will_paginate @posts %>
</div>
<br>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Título</th>
      <th>Comentario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.user.name %></td>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.image_url %></td>
        
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="navPag">
  <%= will_paginate @posts %>
</div>
<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/like.js.erb
$("#curtir").replaceWith("<%= escape_javascript(render('posts/like')) %>");
$("#descurtir").replaceWith("<%= escape_javascript(render('posts/dislike')) %>");

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
  <%= image_tag(@post.image_url)  if @post.image.present? %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<% if logged_in? %>
  <%= render 'like' %>
  <%= render 'dislike' %>
<% end %>

<%= form_for @comment, url: :comment_post do |f| %>
  <%= f.text_field :content%>
  <%= f.submit "Comentar" %>
<% end %>

<% @comments.each do |comment| %>
  <p><%= comment.content %></p>
  <p><%= link_to "Editar", edit_comment_post_path(comment)%></p>
<% end %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', feed_path %>