config/routes.rb
Rails.application.routes.draw do
  
  resources :comments
  
  get 'posts/feed', to: 'posts#feed', as: :feed
  delete 'posts/destroy/:id', to: 'posts#destroy', as: :post_destroy
  resources :posts
  
  post 'posts/:id/comments', to: 'comments#create', as: :comment_post
  get 'posts/comment/:id', to: 'comments#edit', as: :edit_comment_post
  patch 'posts/:id/like', to: 'posts#like', as: :like_post
  patch 'posts/:id/dislike', to: 'posts#dislike', as: :dislike_post
  
  
  # Rotas de UserController
  get 'users/admin', to: 'users#crud', as: :admin
  get 'users', to: 'users#index', as: :users
  get 'users/new', to: 'users#new', as: :user_new
  post 'users/new', to: 'users#create'
  get 'users/:id', to: 'users#show', as: :user
  get 'users/edit/:id', to: 'users#edit', as: :user_edit
  patch 'users/edit/:id', to: 'users#update'
  delete 'users/destroy/:id', to: 'users#destroy', as: :user_destroy
  
  #Rotas de SessionsController
  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: :logout
  

  
end

app/views/layouts/_messages.html.erb
<!-- Ira exibir os possiveis erros de operacoes do nosso sistema
Cores, :success => verde, :info => azul, :warning => amarelo, :danger => vermelho
-->
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
    <a class="close" data-dismiss="alert">&#215;</a>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> Mural das Ideias</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <% if logged_in?%>
      <div id="user-detail">

      <p> <span class="usuer">BEM VINDO <%= current_user.name %> </span><%=link_to "Editar conta", user_edit_path(current_user.id) %> <%= link_to "Logout", logout_path, method: :delete %></p>
    
    </div>
    <% end %>

    <h1> Mural das Ideias - IN Junior</h1>
      <% if !current_user%>
        <%= link_to 'Login', login_path %>
      <% end %>
      
      <% if current_user && current_user.admin%>
        <%= link_to 'Usuários', admin_path %>
        <%= link_to 'Posts', posts_path %>
      <% end %>
      <%= link_to 'Novo Usuário', user_new_path %>
      <%= link_to 'Feed', feed_path %>
      
    </header>
    

    
    <%= render 'layouts/messages'%>
    
    <%= yield %>
  </body>
</html>